### PR TITLE
feat: stringifyWithIdentation -> add method similar to elm encode

### PR DESCRIPTION
**Pull request by srghma**
## What does this pull request do?

Please describe the purpose of the pull request, including any background context and links to related issues. If this introduces a large change to the project, please describe what you have implemented.

## Where should the reviewer start?

Help save the reviewer time by highlighting the most important sections of code.

## How should this be manually tested?

If this is a new feature, you should provide new test coverage. If it fixes an existing bug, you should provide a failing test case this change fixes. Other than automated testing, what manual tests can the reviewer perform to verify your work?

## Other Notes:

Does the project documentation need to be updated? Should we introduce a new example, or update any existing examples? Does this PR require any other follow-up tasks?

### CODE REVIEW

**Comment by srghma** [comment]
ah, it exists already, two times https://github.com/purescript-contrib/purescript-argonaut-core/pull/29

**Comment by thomashoneyman** [comment]
@srghma thanks for your contributions lately!  For future PRs, do you mind editing the issue template to briefly describe your addition? For something small like this you can remove most of it and just write the “What does this pull request do?” section.

**Comment by srghma** [comment]
@thomashoneyman added, tnx, cannot reopen

**Comment by srghma** [comment]
@thomashoneyman I have already added the description

could you reopen this pr so that we could resume confersation

I have closed this pr by mistake and cannot reopen it again

**Comment by srghma** [comment]
the `files changed` tab right now shows typo `identation` instead of `indentation` for this pr

but I have already fixed this by force push

if you reopen it github should update the code

**Comment by thomashoneyman** [comment]
I’m not able to open the pull request either (the button to do so is disabled). Mind opening another PR?

**Pull request closed without merging**
