### PR TITLE
Updates for 0.9.1

### PR DESCRIPTION
**Pull request by kRITZCREEK**

### CODE REVIEW

**Comment by kRITZCREEK** [comment]
restarting ci

**Comment by garyb** [comment]
I was half way through doing the various `argonaut` repos too :wink:

**Comment by kRITZCREEK** [comment]
Allright in that case I'll just close this?^^

**Comment by garyb** [comment]
I think this was probably fine, just needed the build updating so as to not use the travis image that sucks, etc. Thanks though! I'll get this and the rest up to date in about 30 mins probably.

**Comment by kRITZCREEK** [comment]
Allright thanks for all your hard work!

**Pull request closed without merging**
