### PR TITLE
Rename and export stringify

### PR DESCRIPTION
**Pull request by charleso**
Apologies if there's a reason for not exporting this in the first place.

### CODE REVIEW

**Comment by garyb** [comment]
It's not exported directly because `show` is the same thing... `show` probably should be something else though, so that it fits the informal law of printing valid PS code, so :+1: I think.

**Comment by charleso** [comment]
Yeah I don't like `Show`, it can cause subtle bugs when types change. :)

**Comment by damncabbage** [comment]
In case it's useful: the opening post of https://github.com/purescript/purescript/issues/1675 lays out the objection to enforcing the use of `Show` pretty well:

> The more types that do have Show instances, the more dangerous show becomes; given that it works on almost anything, and that the return type is just String (rather than something that mentions the input type like pure, for example) it's very easy to call show on the wrong thing. It's almost like using a dynamic language!

**Comment by garyb** [comment]
Oops, sorry this was left to languish!

**Pull request merged**
